### ISSUE TITLE
Logo Proposal 

### ISSUE THREAD

**Issue by Tobaloidee** [emericg/WatchFlower#1]
Hello @emericg  Good day!! I am a graphic artist and an open source enthusiast.. I would like to  contribute to your project by designing a logo for free. Actually I already designed one for this project as I found it interesting. I hope you like it and consider using it! -[Tobaloidee](https://steemit.com/@tobaloidee)

- The design is simple but memorable. It is unique as it embodies the initial of your project which is "W" placed in part of the flower/plant. Still open for your suggestions if you have any. :)

![watchflower-01-01-01-01](https://user-images.githubusercontent.com/36028424/56413106-eeb73780-62b8-11e9-8b2a-c5f7448475bf.png)

How it will look in ReadME
![readme](https://user-images.githubusercontent.com/36028424/56413565-810c0b00-62ba-11e9-8a4f-d486e3e03725.png)

If you like it, I will finalize the files and make a PR for it!

**Comment by Tobaloidee** [comment]
I understand @emericg  I will check your other project and try to make a logo for it! closing this issue now.

**Comment by emericg** [comment]
Yes it's a really cool icon, and thank you for taking some time to work on this.
I'm sorry but as we discussed, a whole new visual design for both icon and UI are already well underway, and so I cannot accept your proposition :(
