### ISSUE TITLE
Add noting function

### ISSUE THREAD

**Issue by FYr76** [emericg/WatchFlower#14]
I would like to have a noting function with the possibility to add photo's, like in the original app. It gives other options to track the growth in the long term. What do you think about the following repository? 
https://github.com/7LPdWcaW/GrowTracker-Android

**Comment by emericg** [comment]
I'm not sure I understand the feature.
Like an history screen / timeline, where you can post timestamped photos and notes (text fields) ?

**Comment by FYr76** [comment]
Yes, you're right, just like a plant diary/ activity log. I used it a lot in the original app. A reminder / schedule function could be handy too. This app is a prettier example: https://play.google.com/store/apps/details?id=us.crema.vera

**Comment by emericg** [comment]
Better late than never, but I'm working on this feature ^^ See attached pictures. Let me know if that's what you had in mind.

![Capture d’écran de 2022-03-02 15-29-19](https://user-images.githubusercontent.com/691258/156381432-fe5f287a-7a76-43ec-9038-4fa5c9260d0c.png)
![Capture d’écran de 2022-03-02 15-29-26](https://user-images.githubusercontent.com/691258/156381437-e9afc244-561e-4605-9b51-59b02898613a.png)

**Comment by h3rm** [comment]
> Better late than never, but I'm working on this feature ^^ See attached pictures. Let me know if that's what you had in mind.
> 
> ![Capture d’écran de 2022-03-02 15-29-19](https://user-images.githubusercontent.com/691258/156381432-fe5f287a-7a76-43ec-9038-4fa5c9260d0c.png) ![Capture d’écran de 2022-03-02 15-29-26](https://user-images.githubusercontent.com/691258/156381437-e9afc244-561e-4605-9b51-59b02898613a.png)

yeah, niceee! can't wait until you release it ✌️

**Comment by emericg** [comment]
Alright so this is now release!

> idea: can you maybe also add a function that makes a screenshot of the monthly overview of each sensor/flower care of "DATA"

Not easily no. I'll add the possibility soon to do next/previous months soon though, so the history graphs are more useful.
