### ISSUE TITLE
Parrot Pot : moisture doesn’t recognize 

### ISSUE THREAD

**Issue by ezdeham** [emericg/WatchFlower#22]
Hi,

I have a Parrot pot and I just downloaded your iOS app.
Everything works fine except he doesn’t recognize the moisture. (See screenshot)
![00E29204-A866-49C9-B13B-3F44BE6E232C](https://user-images.githubusercontent.com/42421818/104979329-4fcaec80-5a04-11eb-8232-392232c12a95.png)

Can you please help me?

Best regards,
Daniel

**Comment by emericg** [comment]
Hi!
Unfortunately the Parrot Pot support is still very theoritical... I've been trying to get one for some time, with no success so far.
There are a couple of differences between the pots and the flower powers, and there is no informations online (noone ever did a third party support for these devices).

I'm gonna publish a new WatchFlower version (probably tomorrow) with changes for the Parrot Pot , let me know if the values are better.
In the mean time I'm still trying to buy one to test properly and get everything working (including the automatic watering).

**Comment by ezdeham** [comment]
If you live in Netherlands, I have one extra and I can send it to you.
It has a problem that it’s not working on battery and I don’t know what is wrong with it

**Comment by ezdeham** [comment]
I did the update, apparently it works better but the new problem is numbers and percentages don't make sense.
![image](https://user-images.githubusercontent.com/42421818/105630580-544f3500-5e4a-11eb-9703-ee56c25e2506.png)

**Comment by emericg** [comment]
Yeah that's actually worse...
Unfortunately I live in France. I'll keep looking for a second hand unit with an affordable price (some people seems to think parrot pot are collectibles, and worth a lot...)

**Comment by ezdeham** [comment]
I found a lot of them in marketplace of facebook in France.
Please check it:
https://www.facebook.com/marketplace/item/766040890838475/

**Comment by emericg** [comment]
I don't use Fb I hadn't thought about it. I sent a few messages.
So far same problem, either ludicrous prices or no shipping...

**Comment by emericg** [comment]
Just to let you know, I've sent another round of message to a couple of sellers, I didn't forget about the parrot pot!

**Comment by emericg** [comment]
Alright it costed me 32€, but this will be FIXED in the next release. I also figured out how to read the water tank level.
I'll **try** to research how to do a manual watering, and maybe automatic watering (set a low limit to trigger watering) but that's really a MAYBE.

**Comment by ezdeham** [comment]
Thanks a lot!
I can't wait until next update 😁
I hope you also find a way to automatic/manual watering!
Then I'll buy more of this pot

**Comment by emericg** [comment]
I think the manual watering trigger is OK but it needs an UI, I'll do that later.
The history synchronization for the parrot device is documented, I think it's possible to make it work too. Again, later :p

**Comment by emericg** [comment]
I'm closing this issue, if you want to add some informations feel free to do so.
