### ISSUE TITLE
On iOS there is no safe space left for home indicator at the screen bottom

### ISSUE THREAD

**Issue by giedrius-stanevicius** [emericg/WatchFlower#24]
Notice how at the bottom iOS bar overlaps the app buttons (PS: don't worry about the sensor data - I'm just playing with my Arduino): 
<img src="https://user-images.githubusercontent.com/15320138/106784244-cb5ba900-6654-11eb-9802-c41f2b9f4a50.jpeg" height="500">

**Comment by emericg** [comment]
Indeed I never set that up. I'll have a look at it one of these days.
Glad to see someone making a custom device ^^ If you are using the v1 (on the master branch) there are many new capabilities for custom sensors (but the database format is not finished yet...).

**Comment by emericg** [comment]
I'm closing this because this should be fixed in the next release of the app, and with other improvements related to safe spaces.
Feel free to reopen if this is not good enough!
