### ISSUE TITLE
Sensor doesn't show graph dots

### ISSUE THREAD

**Issue by brechtneven** [emericg/WatchFlower#41]
First let me compliment you with your app, Very well made!

I just got some Xiaomi sensors and noticed that suddenly one of them isn't able to show graph dots anymore, which I find a very nice feature. All other behave like they should. Also I just noticed that battery level is at -1% and firmware is UNKN. 
Didn't had this issue yesterday. Since I just got them, I can still return them. You think I got a faulty sensor?

**Comment by emericg** [comment]
Hi!
The graph dots are shown until there is 16 data records or more. Maybe I can set the limit a little higher. However with a synchronized sensor and hundreds of records like below it would be unreadable with points.
![104851682-cf6a9580-58f6-11eb-964f-014211d30e87](https://user-images.githubusercontent.com/691258/115988783-842de600-a5bb-11eb-8c57-e042d9255726.png)

Also battery and firmware not set is not really important, and probably a bug in the app not a faulty sensor. I'll have a look I might know why it could happen.

**Comment by emericg** [comment]
I'm closing this issue, if you want to add some informations feel free to do so.
