### ISSUE TITLE
[Feature request] Blacklist device(s)

### ISSUE THREAD

**Issue by AurelienKun** [emericg/WatchFlower#42]
Hi, I love this app. It is so great that I bought more sensors for my house. 
Unfortunately, the application detects also my neighbour's sensor as I live in apartment in a city. 
So, could it be possible to implement a blacklist somewhere to avoid this situation ?

Thank's a lot 👍🏻

**Comment by emericg** [comment]
Hi.
Yes that sounds like an useful feature.
I thought about it in the past, using the wireless connection strength to limit the scanning "range". I'll try to think it through and come up with a proper feature.

In the mean time you can delete the unwanted sensors using long press on a sensor, or middle mouse click right?
Sensors are only added after a scan, so at least they should not reappear each time you use the app.

**Comment by AurelienKun** [comment]
Oh nice ! I didn't know about the middle click (Linux version here). Good to know ! Thank's ! It's a good workaround for now ^^
Do I leave this ticket open until you implement a more proper way ? @emericg

**Comment by emericg** [comment]
Sure you can leave this issue open, I'll update it when progress are made.

**Comment by emericg** [comment]
I'm closing this issue, with the next version you will be able to blacklist any device around you:

![Capture d’écran de 2022-03-02 15-26-56](https://user-images.githubusercontent.com/691258/156380804-8499fcba-3bf8-4326-bb7a-d4d9e071738a.png)
