### ISSUE TITLE
After using Blink LED function the LED does not stop blinking

### ISSUE THREAD

**Issue by notsven** [emericg/WatchFlower#44]
I used the Blink LED function on my xiaomi flower care sensor.
Somehow the LED does not stop blinking since and already consumed a whole battery.

**Comment by emericg** [comment]
This is very peculiar...
Is it still doing it after a battery change?

I can probably add some code so it force disable the LED when syncing (so if it got stuck, it would deactivate on the next sync) but this is usually done by the sensor itself, so I guess it's a bug in the sensor firmware.

**Comment by emericg** [comment]
I've added some code to (try and) check if the LED was kept ON. It will be in the next relase.
