### ISSUE TITLE
Custom high/low values per device

### ISSUE THREAD

**Issue by Kernald** [emericg/WatchFlower#46]
Looking at plant monitoring sensors, the reading have (sane) defaults for low and high values (e.g. moisture) depending on whether the plant is inside or outside. It's neat, but it would be great to be able to customise that for plants with specific needs (e.g. succulents don't need as much moisture as strawberries).

**Comment by emericg** [comment]
Hi,
I'm not sure I understand your problem. The values on the "limits" screen are sliders, you can already customize them per sensor.

**Comment by Kernald** [comment]
Ha you're right, thanks! Sorry I didn't realise they were sliders. That's exactly what I was looking for :-)
