### ISSUE TITLE
Watchflower pasted from the clipboard

### ISSUE THREAD

**Issue by fluxens** [emericg/WatchFlower#54]
**Describe the bug**
Got a message telling  me that watchflower accessed my clipboard.

**Expected behavior**
Should not access my clipboard. what's happening here?

**Screenshots**
![Screenshot_20211214-010102](https://user-images.githubusercontent.com/22811368/145908354-feb0e6f8-a6a7-4cff-91d6-020d9b699e1f.png)

**Your environment**
Android 12

**Comment by emericg** [comment]
Another breaking change from Android 12, add it to the list...
WatchFlower doesn't use the clipboard (at all), but somehow it's producing a warning anyway.

It's probably a bug (?) in a software library that is used by the app, it will be tracked here with other developers having the same problem: https://bugreports.qt.io/browse/QTBUG-98412

**Comment by emericg** [comment]
I'e updated the app to the latest Qt 6 release, this bug should be fixed. I'll let you know when the beta is available for testing.
