### ISSUE TITLE
[Feature Request] Please add Xiaomi Qingping Bluetooth Smart Alarm Clock support

### ISSUE THREAD

**Issue by EcherArt** [emericg/WatchFlower#60]
**Is your feature request related to a problem? Please describe.**
While this device is indeed an alarm clock, it also has temperature and humidity sensor. Unfortunately I cannot use it with your app right now, but I saw Xiaomi Digital Hygrometer Alarm Clock and QingPing Temp RH Lite clock supported, so I hope it's possible for my device to be integrated.

**Describe the solution you'd like**
WatchFlower discovering the device via Bluetooth and connecting to it.

**Describe alternatives you've considered**
Buying another device 

**Additional context**
Clock in question (pic from aliexpress):
https://ae01.alicdn.com/kf/H335313b8c5a3472c98a790ef9d09d550S/Xiaomi-Qingping-Bluetooth-Alarm-Clock-3-in-1-Temperature-Humidity-Sensor-Monitor-Mijia-Night-Light-Mihome.jpg

Clock's official page from Quingping: https://www.qingping.co/bluetooth-alarm-clock/overview

**Comment by emericg** [comment]
Yes I will try to add this device, but because I don't have it myself I hope that I can find the relevant information on the Internet.

**Comment by EcherArt** [comment]
Thank you! I have the device so if I can help you by sending the logs/photos, I'll be good to do so.

**Comment by emericg** [comment]
Ok so I think I've got this mostly implemented, I just need one more bit of infos.
Can you run _nRF Connect_ software, and get me the Bluetooth name of the device?

And if you want to be thorough, connect to the device and get a screenshot of the services, like so:
![nrf_connect_device](https://user-images.githubusercontent.com/691258/168110278-e643e047-be7a-4cb1-88f8-0ef65b0fc676.png)

Thanks

**Comment by EcherArt** [comment]
Hello, thank you so much!
Here is what I found by connecting to the device:

![Screenshot_20220513-220750](https://user-images.githubusercontent.com/22240259/168373983-93ef90f6-7c7a-409c-a31b-003ac2209269.jpg)
![Screenshot_20220513-220827](https://user-images.githubusercontent.com/22240259/168374010-2c26f2bd-f29b-46f3-93a6-05b45995a114.jpg)
![Screenshot_20220513-220843](https://user-images.githubusercontent.com/22240259/168374042-1cd40c1c-6f78-49f8-beb9-971a3949ac58.jpg)

**Comment by EcherArt** [comment]
That's awesome, thank you! 

Hopefully it'll help:

![Screenshot_20220524-204748](https://user-images.githubusercontent.com/22240259/170100290-796ad8d3-6283-4de7-993f-4e21c750f75b.jpg)
![Screenshot_20220524-204847](https://user-images.githubusercontent.com/22240259/170100333-026e450f-35dc-423d-a6b9-59204884888d.jpg)

**Comment by emericg** [comment]
Send me an email with your Google account (or iCloud account) and I'll add you to the testers for the new version!

**Comment by emericg** [comment]
Sorry I just assume everyone is on mobile...
It's even easier to test on linux, just pick up a build from here: https://github.com/emericg/WatchFlower/actions/runs/2469137999

**Comment by emericg** [comment]
Did you have a chance to test this?

**Comment by EcherArt** [comment]
Yes, sorry for the late request, it does work!
![image](https://user-images.githubusercontent.com/22240259/176182325-3a2605bc-cce9-49c7-987e-fa631f4cb6c2.png)

**Comment by emericg** [comment]
Great thanks for testing this!
