### ISSUE TITLE
[Feature Request] Integration with Google Home and/or Vera

### ISSUE THREAD

**Issue by rngarcia** [emericg/WatchFlower#65]
Could the app be integrated with smart home devices such as Vera/Ezlo or Google Home Hub? This would enable to start scenes/triggers such as open the blinds, start the water drip, etc...

**Comment by emericg** [comment]
Unfortunately I don't have any smart home devices, and working on that would really be way too much work...
Some more generic approach like the IFTTT would be better suited for this application, given the low number of users and even lower number of developers :p
