### ISSUE TITLE
Date choose is not possible on journal entry

### ISSUE THREAD

**Issue by andrelsr** [emericg/WatchFlower#67]
Hi,
When I click on the date to edit it when adding a new entry on journal, the days appear all crumpled on upper lef side of calendar. So I can't choose the date.
![Screenshot_2022-06-26-16-27-48-432_com emeric watchflower](https://user-images.githubusercontent.com/64709375/175831043-ad4e787f-c96f-4ddf-b16c-2e559bc1aa64.jpg)

I didn't notice the journal before, it will be very useful.
Android, app v4.0

**Comment by emericg** [comment]
Yes the version 4.0 has been released yesterday, it has many other new features than the journal, like background updates and notifications ^^

> When I click on the date to edit it when adding a new entry on journal, the days appear all crumpled on upper lef side of calendar.

Indeed it looks like this bug slip into the final release. I'll fix it tomorrow and release a new version very soon, thanks for reporting it!

**Comment by emericg** [comment]
Ok version 4.1 has been released with this bug fixed.
