### ISSUE TITLE
[Feature Request] BTHome Format Support?

### ISSUE THREAD

**Issue by ankushg** [emericg/WatchFlower#76]
**Is your feature request related to a problem? Please describe.**
I've got a few sensors that I've flashed with the [pvvx/ATC_MiThermometer](https://github.com/pvvx/ATC_MiThermometer) firmware.

I'm broadcasting with the BTHome format instead of Xiaomi, because it's an open standard that allows devices to broadcast their sensor data and button presses without being tied to a specific manufacturer. It's well-supported by other projects like Home Assistant as well!

**Describe the solution you'd like**
It would be great if WatchFlower could support the [BTHome format](https://bthome.io/) too!

The format is quite well-documented: https://bthome.io/format/

Supporting BTHome could also reduce the effort it takes this project to maintain pages like the [custom sensor page](https://github.com/emericg/WatchFlower/blob/master/docs/howto-custom-sensor.md), and also adds support for cool devices like the open-source [b-parasite](https://github.com/rbaron/b-parasite) soil moisture sensor

**Comment by emericg** [comment]
Thank you for linking the documentation.
It does look like a well written doc indeed, I think I can add support for the format this week.
I'll get back to you when I know more about these firmwares, but I should probably flash one device to see what's what.

**Comment by emericg** [comment]
Alright everything should be working with the ATC firmware, and there shouldn't be much missing to also support the b-parasite now.
Many of the documentation pages have been updated too while I was at it.

**Comment by emericg** [comment]
Closing, this issue is solved in v5.0
