### ISSUE TITLE
Time sync doenst work

### ISSUE THREAD

**Issue by bykewix** [emericg/WatchFlower#78]
Hello!

Time synchronization used to work, but now it doesn't.

It affects the following type: LYWSD02MMC

Ty guys

**Comment by emericg** [comment]
Hi,
Can you try to manually refresh the sensor, and see if the time is then synced?
The updates are now done differently (faster for temp. readings) without the need of an explicit Bluetooth connection (needed for a time sync), that may be why the time is not synced.

**Comment by emericg** [comment]
I'm sorry, what OS are you using, and what is the "access to new bluetooth connections" setting is?
If it works, I'm closing the issue, but you can still comment if you wish.
