### ISSUE TITLE
[Feature Request] Show battery level

### ISSUE THREAD

**Issue by howels** [emericg/WatchFlower#80]
Please add battery status for the Xiaomi flower care devices. These have monitoring of the internal CR2032 battery status.

Would be very useful to know when to replace batteries.

Using the Android app on Android 13

**Comment by emericg** [comment]
By the way, sorry I never responded but I didn't understand your request.
Battery levels have always been in the app, in the main screen and in the sensor infos?!

![Screenshot_2023-09-28-18-22-58-569_com emeric watchflower](https://github.com/emericg/WatchFlower/assets/691258/15f3c34c-32f7-44d8-88f8-06112d6181f4)

![Screenshot_2023-09-28-18-23-16-230_com emeric watchflower](https://github.com/emericg/WatchFlower/assets/691258/6ce8a010-846f-48c5-928f-14cfb8f565dc)

**Comment by howels** [comment]
> By the way, sorry I never responded but I didn't understand your request. Battery levels have always been in the app, in the main screen and in the sensor infos?!
> 
> ![Screenshot_2023-09-28-18-22-58-569_com emeric watchflower](https://user-images.githubusercontent.com/691258/271350834-15f3c34c-32f7-44d8-88f8-06112d6181f4.jpg)
> 
> ![Screenshot_2023-09-28-18-23-16-230_com emeric watchflower](https://user-images.githubusercontent.com/691258/271350909-6ce8a010-846f-48c5-928f-14cfb8f565dc.jpg)

I do see the battery level on one device but only one out of 4 identical devices shows the battery level.
Also, on Android the app somehow overlaps with my status bar which nothing else does.
![Screenshot_20230928-174550](https://github.com/emericg/WatchFlower/assets/7933842/68f132df-22b8-44e3-afbb-31a621ddf448)
![Screenshot_20230928-174537](https://github.com/emericg/WatchFlower/assets/7933842/64a75414-0e94-43d3-926a-4c48f4580a61)
![Screenshot_20230928-174451](https://github.com/emericg/WatchFlower/assets/7933842/a1df723a-52e8-44ac-b15e-beded750b90c)

**Comment by emericg** [comment]
> I do see the battery level on one device but only one out of 4 identical devices shows the battery level.

I'm not sure what to say about that, the battery level won't show if the value from the flower care is really weird (not in the 0-100% range), so it's possible the problem is on the sensors.

> Also, on Android the app somehow overlaps with my status bar which nothing else does.

Damn I'm really sorry about that, it's been a really tricky issue on the last couple release. I guess your phone has no notch?
I'll be doing a release in the next couple days.

**Comment by howels** [comment]
> > I do see the battery level on one device but only one out of 4 identical devices shows the battery level.
> 
> I'm not sure what to say about that, the battery level won't show if the value from the flower care is really weird (not in the 0-100% range), so it's possible the problem is on the sensors.
> 
> > Also, on Android the app somehow overlaps with my status bar which nothing else does.
> 
> Damn I'm really sorry about that, it's been a really tricky issue on the last couple release. I guess your phone has no notch? I'll be doing a release in the next couple days.

Hmm. I used to get erroneous low battery readings just after replacing the CR2032 cells, possible that the sensor is incorrectly calibrated.

I run a Sony Xperia 1 III, no cutout here.

**Comment by emericg** [comment]
> Hmm. I used to get erroneous low battery readings just after replacing the CR2032 cells, possible that the sensor is incorrectly calibrated.

Yeah that would certainly make sense, either the FlowerCares are not reading the battery voltages correctly, or the CR2032 cells you are using are not working in the usual range (but that would be weird though).

> I run a Sony Xperia 1 III, no cutout here.

Ok I've pushed a new version to Android beta channel, it will be published as soon as it passes the store automated checks, can you take a look at it and see if it fixes your issue?

**Comment by howels** [comment]
Apologies for not replying - I see a battery warning now on one device. I think my units have inaccurate voltage sensors or something.

**Comment by emericg** [comment]
No problem, the battery problem probably wasn't like we discussed, and the header problem has been solved by the 5.3 release a while ago, that's why I closed this issue.
